version: 2.1


orbs:
  general: bjd2385/general@0.2.0
  orb-tools: circleci/orb-tools@11.5.0
  shellcheck: circleci/shellcheck@3.1.2


executors: {}


commands: {}


jobs:
  orb-pack:
    executor: default
    resource_class: small
    parameters:
    steps:
      - checkout
      - circleci-cli/install
      - run:
          command: |
            # Reduce nested commands and jobs to files under src/commands or src/jobs so they can be packed by 'circleci orb pack src/'.
            # Allows you to group collections of commands under directories.

            pre-pack()
            {
                local current_directory="$1"
                local d

                cd "$current_directory" || exit 1
                pwd

                find . -maxdepth 1 -mindepth 1 -type d -print0 | xargs --null -I % basename % | while read -r d; do
                    if [ -n "$(ls "${d}")" ]; then
                        # Drop one level below before processing all of the files and pack those sub-subdirectories into the current subdirectory.
                        pre-pack "$d"
                        find "$d" -maxdepth 1 -mindepth 1 -type f -print0 | xargs --null -I % basename % | while read -r f; do
                            fname="$(basename "$f")"
                            if [ ! -f "${d}-${fname}" ]; then
                                cp "${d}/${f}" "${d}-${fname}"
                            fi
                        done
                    else
                        printf "INFO: Ignoring '%s', module is empty.\\n" "${SRC}/${TYP}/${d}"
                    fi
                done

                cd ..

                return 0
            }

            find src/ -maxdepth 1 -mindepth 1 -type d -print0 | xargs -I % basename % | xargs -I % pre-pack src/%
            mkdir -p dist/
            circleci orb pack --skip-update-check src/ > dist/orb.yml

      - persist_to_workspace:
          paths:
            - orb.yml
          root: ./dist


workflows:
  on-tag:
    jobs:
      - general/orb-pack:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - orb-tools/publish:
          name: publish production orb
          enable-pr-comment: false
          vcs-type: << pipeline.project.type >>
          orb-name: bjd2385/general
          pub-type: production
          requires:
            - general/orb-pack
          context:
            - development
            - orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

  on-commit:
    jobs:
      # # Run a bunch of tests against this repo
      # - orb-tools/lint

      - general/orb-pack:
          filters:
            branches:
              ignore: master

      - shellcheck/check:
          exclude: SC2148
          filters:
            branches:
              ignore: master

      - orb-tools/publish:
          name: publish development orb
          enable-pr-comment: true
          vcs-type: << pipeline.project.type >>
          orb-name: bjd2385/general
          pub-type: dev
          requires:
            - general/orb-pack
            - shellcheck/check
          context:
            - orb-publishing
            - github
          filters:
            branches:
              ignore: master
